alborz_school_site/alborz_school_site/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.index.urls",namespace="index")),
    path("account/", include("apps.account.urls",namespace="account")),
    path("blogs/", include("apps.blog.urls",namespace="blog")),
    path('ckeditor',include('ckeditor_uploader.urls')),

]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

# ----------------------------------------------- error handling
handler404='apps.errorhandlers.views.handler404'

alborz_school_site/apps/account/urls.py
from django.urls import path
from .views import RegisterUserView,VerifyRegisterUserView,LoginUserView,ChangePasswordView,RememberPasswordView,LogoutUser,UserPanelView

app_name='account'
urlpatterns = [
    path('register/',RegisterUserView.as_view(),name='register'),
    path('verify/',VerifyRegisterUserView.as_view(),name='verify'),
    path('login/',LoginUserView.as_view(),name='login'),
    path('logout/',LogoutUser.as_view(),name='logout'),
    path('change_password/',ChangePasswordView.as_view(),name='changepassword'),
    path('remember_password/',RememberPasswordView.as_view(),name='rememberpassword'),
    path('userpanel/',UserPanelView.as_view(),name='userpanel'),
    # path('userpanel/',UserPanelView.as_view(),name='userpanel'),
    # path('userpanel_orders/',UserPanelOrdersView.as_view(),name='userpanel_orders'),
    # path('userdetail_modify_informations/',UserUpdateDetail.as_view(),name='userdetail_modify_informations'),
    # path('userdetail_modify_password/',UserPasswordChange.as_view(),name='userdetail_modify_password'),
    # path('username_form_validation/',check_user_name_validation_ajax,name='username_form_validation'),
]

alborz_school_site/apps/blog/urls.py
from django.urls import path,include
from .views import BlogsView

app_name='blog'
urlpatterns = [
    path("",BlogsView.as_view(),name='blogs' ),
    # path("blog/",BlogsView.as_view(),name='blogs' ),
]

alborz_school_site/apps/index/urls.py
from django.urls import path,include
from .views import IndexView,ContactUsView,AboutUsView,TeacherListView

app_name='index'
urlpatterns = [
    path("",IndexView.as_view(),name='home' ),
    path("contact-us/",ContactUsView.as_view(),name='contact' ),
    path("about-us/",AboutUsView.as_view(),name='about_us' ),
    path("teacher-list/",TeacherListView.as_view(),name='teacher_list' ),
]

alborz_school_site/templates/partials/advert.html
{% if advert == 1 %}
    <div class="py-4">
        <section class="container  col-10">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-6 text-center text-lg-end">
                    <h1 class="display-6 mb-3">کسب رتبه <span class="text-warning">نخست</span> دربین مدارس ایران </h1>
                    <p class="lead text-muted text-justify mb-3">
                        لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.                </p>
                    <div class="d-flex justify-content-lg-start justify-content-center">
                        <a href="#" class="btn btn-primary w-25" >
                            مطاله بیشتر
                            &nbsp;
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                            </svg>
                        </a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <img src="{{media_url}}/images/png/Teacher-cuate.png" alt="" class="img-fluid">
                </div>
            </div>
        </section>
    </div>
{% elif advert == 2 %}
    <div class="bg-warning py-5">
        <section class="container col-10">
            <div class="row align-items-center">
                <div class="col-lg-6">
                    <img src="{{media_url}}/images/png/Online calendar-amico.png" alt="" class="img-fluid">
                </div>
                <div class="col-lg-6 text-center text-lg-end">
                    <h2 class="display-4 mb-3">خدمات <span class="text-white">مشاوره</span> و <span class="text-white">برنامه ریزی</span></h2>
                    <p class="lead text-muted text-justify mb-3">
                        لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.                </p>
                    <div class="d-flex justify-content-lg-start justify-content-center">
                        <a href="#" class="btn btn-primary w-25" >
                            مطالعه بیشتر
                            &nbsp;
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% else %}
    <div class="py-5 text-white" style="background-color: #7a27fc;">
        <section class="container col-10">
            <div class="row align-items-center">
                <div class="col-lg-6 text-center text-lg-end">
                    <h2 class="display-4 mb-3">کلاس های <span class="text-warning">رایگان</span> آنلاین </h2>
                    <p class="lead text-justify mb-3">
                        لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.                </p>
                    <div class="d-flex justify-content-lg-start justify-content-center">
                        <a href="#" class="btn btn-warning w-25" >
                            مطالعه بیشتر
                            &nbsp;
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                            </svg>
                        </a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <img src="{{media_url}}/images/png/Online learning-cuate.png" alt="" class="img-fluid">
                </div>
            </div>
        </section>
    </div>
{% endif %}

alborz_school_site/templates/partials/footer.html
<div class="py-5 bg-dark">
    <footer class="container col-10 text-light ">
        <div class="row justify-content-center">
            <div class="col-lg-5 offset-1 align-self-center">
                <h2 class="text-center text-lg-end">راه های ارتباطی</h2>
                <p class="text-center text-lg-end text-secondary">آدرس (شعبه ۱) &nbsp;: خیابان مستوفی نبش کوچه لادن پلاک ۴۱</p>
                <p class="text-center text-lg-end text-secondary">آدرس (شعبه ۲) &nbsp;: خیابان میرداماد نبش کوچه عزیزیان پلاک ۱۰۹</p>
                <p class="text-center text-lg-end text-secondary">آدرس (شعبه ۳) &nbsp;: خیابان زعفرانیه نبش کوچه شهید اکبری پلاک ۶۹</p>
                <hr>
                <p class="text-center text-lg-end">تلفن گویا &nbsp;:&nbsp; ۴۵۴۵۰۰۰۹</p>
                <hr>
                <div class="d-flex flex-wrap flex-lg-nowrap text-lg-end">
                    <div class="col-lg-3 col-12 p-0 text-center text-lg-end text-warning">صفحات اجتماعی ما :</div>
                        <div class="col-12 col-lg-4">
                            <ul class="list-unstyled d-flex justify-content-lg-start  justify-content-center p-0">
                                <li class="px-1">
                                    <a href="#" class="text-light">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telegram" viewBox="0 0 16 16">
                                            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.287 5.906c-.778.324-2.334.994-4.666 2.01-.378.15-.577.298-.595.442-.03.243.275.339.69.47l.175.055c.408.133.958.288 1.243.294.26.006.549-.1.868-.32 2.179-1.471 3.304-2.214 3.374-2.23.05-.012.12-.026.166.016.047.041.042.12.037.141-.03.129-1.227 1.241-1.846 1.817-.193.18-.33.307-.358.336a8.154 8.154 0 0 1-.188.186c-.38.366-.664.64.015 1.088.327.216.589.393.85.571.284.194.568.387.936.629.093.06.183.125.27.187.331.236.63.448.997.414.214-.02.435-.22.547-.82.265-1.417.786-4.486.906-5.751a1.426 1.426 0 0 0-.013-.315.337.337 0 0 0-.114-.217.526.526 0 0 0-.31-.093c-.3.005-.763.166-2.984 1.09z"/>
                                        </svg>
                                    </a>
                                </li>
                                <li class="px-1">
                                    <a href="#" class="text-light">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                                            <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
                                        </svg>
                                    </a>
                                </li>
                                <li class="px-1">
                                    <a href="#" class="text-light">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
                                            <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
                                        </svg>
                                    </a>
                                </li>
                            </ul>
                        </div>
                </div>
            </div>
            <div class="col-lg-2 col-5 text-center  align-self-start">
                <h4 class="border-end border-3 px-2 text-md-end border-primary">صفحات عضویت</h4>
                <ul class="list-unstyled px-3 text-md-end">
                    {% if user.is_authenticated %}
                        <li><a href=" {% url 'account:userpanel' %} " class="text-decoration-none text-secondary" >پنل کاربری</a></li>
                        <li><a href=" {% url 'account:logout' %}" class="text-decoration-none text-secondary">خروج از حساب کاربری</a></li>
                    {% else %}
                        <li><a href="{% url 'account:register' %}" class="text-decoration-none text-secondary"> ثبت نام در سایت</a></li>
                        <li><a href="{% url 'account:login' %}" class="text-decoration-none text-secondary">ورود به حساب کاربری</a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="col-lg-2 col-5 text-center align-self-start">
                <h4 class="border-end border-3 px-2 text-md-end border-primary">صفحات خبری</h4>
                <ul class="list-unstyled px-3 text-md-end">
                    <!-- <li><a href="#" class="text-decoration-none text-secondary">ثبت نام</a></li> -->
                    {% comment %} <li><a href="/post.html" class="text-decoration-none text-secondary">مقالات</a></li> {% endcomment %}
                    <li><a href="#" class="text-decoration-none text-secondary">مقالات</a></li>
                    <li><a href="#" class="text-decoration-none text-secondary">تاریخ امتحانات میان ترم</a></li>
                    <li><a href="#" class="text-decoration-none text-secondary">تاریخ امتحانات پایانی</a></li>
                </ul>
            </div>
            <div class="col-lg-2 col-5 text-center align-self-start">
                <h4 class="border-end border-3 px-2 text-md-end border-primary">صفحات اطلاعاتی</h4>
                <ul class="list-unstyled px-3 text-md-end">
                    <!-- <li><a href="#" class="text-decoration-none text-secondary">ثبت نام</a></li> -->
                    <!-- <li><a href="#" class="text-decoration-none text-secondary">مقالات</a></li> -->
                    <li><a href="#" class="text-decoration-none text-secondary">فروشگاه</a></li>
                    {% comment %} <li><a href="/about-us.html" class="text-decoration-none text-secondary">درباره ما</a></li> {% endcomment %}
                    <li><a href="#" class="text-decoration-none text-secondary">درباره ما</a></li>
                    {% comment %} <li><a href="/contact-us.html" class="text-decoration-none text-secondary">تماس با ما</a></li> {% endcomment %}
                    <li><a href="#" class="text-decoration-none text-secondary">تماس با ما</a></li>
                </ul>
            </div>
            <hr>
            <div class="col-12 text-start">
                طراحی شده توسط <a href="#" class="text-decoration-none text-warning"> &nbsp;mohammadrz_96</a>
            </div>
        </div>
    </footer>
</div>

alborz_school_site/templates/partials/header.html
<div class="py-4">
    <header class="container col-10">
        <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{{media_url}}/images/blogs/alborz-slider-3.jpeg" class="d-block w-100 rounded" alt="...">
            </div>
            <div class="carousel-item rounded-circle">
                <img src="{{media_url}}/images/blogs/alborz-slider-3.jpeg" class="d-block w-100 rounded" alt="...">
            </div>
            <div class="carousel-item">
                <img src="{{media_url}}/images/blogs/alborz-slider-3.jpeg" class="d-block w-100 rounded" alt="...">
            </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
            </button>
        </div>
    </header>
</div>

alborz_school_site/templates/partials/message.html
{% if messages %}
    {% for message in messages %}
        <h6 class="alert alert-{{message.tags}} my-5 mb-3">
            <div class="">
                <section class="container col-10 col-md-10 col-lg-10">
                    {{message}}
                </section>
            </div>
        </h6>
    {% endfor %}
{% endif %}

alborz_school_site/templates/partials/navbar.html
<div class="my-3 bg-white bg-opacity-95 shadow-sm  sticky-top ">
    <nav class="navbar navbar-expand-lg container col-10"  data-bs-theme="light">
    <div class="container-fluid">
        <a class="navbar-brand fs-4 text-primary" href="#">دبیرستان البرز</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor03">
        <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href=" {% url 'index:home' %} ">خانه</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=" {% url 'blog:blogs' %} ">مقالات</a>
            </li>
            <!-- <li class="nav-item">
                <a class="nav-link" href="#">قابلیت ها</a>
            </li> -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  قابلیت ها
                </a>
                <ul class="dropdown-menu text-center" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href=" {% url 'index:teacher_list' %} ">لیست مدرسین</a></li>
                  <li><a class="dropdown-item" href="#">شرایط ثبت نام</a></li>
                  <li><a class="dropdown-item" href="#">رزرو ثبت نام</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">تاریخ امتحانات میان ترم</a></li>
                  <li><a class="dropdown-item" href="#">تاریخ امحانات خرداد ماه</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item disabled" href="#">فروشگاه</a></li>
                  <!-- <li><a class="dropdown-item" href="#"></a></li> -->
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=" {% url 'index:contact' %} ">ارتباط با ما</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=" {% url 'index:about_us' %} ">درباره ما</a>
            </li>
        </ul>
        <form class="d-flex d-lg-none mb-2" role="search">
            <input class="form-control me-2" type="search" name="q2" placeholder="عبارت مورد نظر را وارد کنید" aria-label="Search">&nbsp;
            <button class="btn btn-outline-primary col-4" type="submit">جست و جو</button>
        </form>

        {% if user.is_authenticated %}
            <div class="d-flex justify-content-lg-end justify-content-start px-3 pt-1" >
                <a href=" {% url 'account:userpanel' %} " class="text-decoration-none fs-5 text-primary" >
                    پنل کاربری
                </a>
            </div>
            <div class="d-flex justify-content-lg-end justify-content-start px-3 pt-1" >
                <a href=" {% url 'account:logout' %} " class="text-decoration-none fs-5 text-primary" >
                    خروج
                </a>
            </div>
        {% else %}
            <div class="d-flex justify-content-lg-end justify-content-start px-3 pt-1" >
                <a href=" {% url 'account:register' %} " class="text-decoration-none fs-5 text-primary" >
                    ثبت نام
                </a>
            </div>
            <div class="d-flex justify-content-lg-end justify-content-start px-3 pt-1" >
                <a href=" {% url 'account:login' %} " class="text-decoration-none fs-5 text-primary" >
                    ورود
                    &nbsp;
                </a>
            </div>
        {% endif %}
        </div>
    </div>
    </nav>
</div>