alborz_school_site/alborz_school_site/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.index.urls",namespace="index")),
    path("account/", include("apps.account.urls",namespace="account")),
    path("blogs/", include("apps.blog.urls",namespace="blog")),
    path('ckeditor',include('ckeditor_uploader.urls')),

]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

# ----------------------------------------------- error handling
handler404='apps.errorhandlers.views.handler404'

alborz_school_site/apps/account/urls.py
from django.urls import path
from .views import RegisterUserView,VerifyRegisterUserView,LoginUserView,ChangePasswordView,RememberPasswordView,LogoutUser,UserPanelView

app_name='account'
urlpatterns = [
    path('register/',RegisterUserView.as_view(),name='register'),
    path('verify/',VerifyRegisterUserView.as_view(),name='verify'),
    path('login/',LoginUserView.as_view(),name='login'),
    path('logout/',LogoutUser.as_view(),name='logout'),
    path('change_password/',ChangePasswordView.as_view(),name='changepassword'),
    path('remember_password/',RememberPasswordView.as_view(),name='rememberpassword'),
    path('userpanel/',UserPanelView.as_view(),name='userpanel'),
    # path('userpanel/',UserPanelView.as_view(),name='userpanel'),
    # path('userpanel_orders/',UserPanelOrdersView.as_view(),name='userpanel_orders'),
    # path('userdetail_modify_informations/',UserUpdateDetail.as_view(),name='userdetail_modify_informations'),
    # path('userdetail_modify_password/',UserPasswordChange.as_view(),name='userdetail_modify_password'),
    # path('username_form_validation/',check_user_name_validation_ajax,name='username_form_validation'),
]

alborz_school_site/templates/account_app/changepassword_form.html
{% extends 'index.html' %}
{% block title %}  تغییر رمز {% endblock title %}
{% block body %}
    <div class="py-5 pb-3">
        <section class="container bg-white rounded col-8 col-md-6 col-lg-4 p-4 shadow">
            <h1 class="text-center display-6  mb-3 text-primary">تغییر رمز حساب کاربری</h1>
            <form action="" method='post'>
                {% csrf_token %}
                {{change_password.as_p}}
                <button type="submit" class="btn btn-primary form-control mb-4">تغییر رمز</button>
            </form>
        </section>
    </div>
{% endblock body %}

alborz_school_site/templates/account_app/login_form.html
{% extends 'index.html' %}
{% block title %}  ورود {% endblock title %}
{% block body %}
    <div class="py-5 pb-3">
        <section class="container bg-white rounded col-8 col-md-6 col-lg-4 p-5 shadow">
            <h1 class="text-center display-6  mb-3 text-primary">ورود به حساب کاربری</h1>
            <form action="" method='post'>
                {% csrf_token %}
                {{login_form.as_p}}
                <div>
                    <a  href=" {% url 'account:rememberpassword' %} " class="remember_password text-decoration-none text-warning">فراموشی رمز عبور</a>
                </div>
                <button type="submit" class="btn btn-primary form-control mt-4">ورود</button>

                {% comment %} <div class="form-group">
                    <div class="form-check"><span class="form-check-input input-check"><span class="input-check__body"><input class="input-check__input" type="checkbox" id="login-remember"> <span class="input-check__box"></span>
                        <svg class="input-check__icon" width="9px" height="7px">
                            <use xlink:href="images/sprite.svg#check-9x7"></use>
                        </svg>
                        </span>
                        </span>
                        <label class="form-check-label" for="login-remember">به خاطر سپاری</label>
                    </div>
                </div> {% endcomment %}
            </form>
        </section>
    </div>
{% endblock body %}

alborz_school_site/templates/account_app/register_form.html
{% extends 'index.html' %}
{% block title %} ثبت نام {% endblock title %}
{% block body %}
    <div class="py-5 pb-3">
        <section class="container bg-white rounded col-8 col-md-6 col-lg-4 p-4 shadow ">
            <h1 class="text-center display-6  mb-3 text-primary">ثبت نام</h1>
            <form action="" method="post" id="register_form">
                {% csrf_token %}
                {{register_form.as_p}}
                <button type="submit" class="btn btn-primary form-control mt-4">ثبت نام</button>
            </form>
        </section>
    </div>
{% endblock body %}

alborz_school_site/templates/account_app/rememberpassword_form.html
{% extends 'index.html' %}
{% block title %}  فراموشی رمز {% endblock title %}
{% block body %}
    <div class="py-5 pb-3">
        <section class="container bg-white rounded col-8 col-md-6 col-lg-4 p-4 shadow">
            <h1 class="text-center display-6  mb-3 text-primary">ورود به حساب کاربری</h1>
            <form action="" method='post'>
                {% csrf_token %}
                {{remember_password.as_p}}
                <button type="submit" class="btn btn-primary form-control mb-4">ورود</button>
            </form>
        </section>
    </div>
{% endblock body %}

alborz_school_site/templates/account_app/user_panel.html
{% extends 'index.html' %}
{% block title %}پنل کاربری{% endblock title %}
{% block body %}
    <div class="py-5">
        <section class="container col-10">
            <h1 class="mb-5 text-center text-lg-end text-primary">پنل کاربری</h1>
            <div class="row g-4 justify-content-around">
                <div class="col-lg-5">
                    <div class="row g-4 text-center">

                        <div class="col-6">
                            <a href="" class="text-decoration-none text-primary">
                                <div class="shadow border bg-white bg-opacity-95 p-3 rounded hover1">
                                    اطلاعات کاربر
                                    <svg class="mx-1" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-vcard" viewBox="0 0 16 16">
                                        <path d="M5 8a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm4-2.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5ZM9 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4A.5.5 0 0 1 9 8Zm1 2.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1-.5-.5Z"/>
                                        <path d="M2 2a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H2ZM1 4a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H8.96c.026-.163.04-.33.04-.5C9 10.567 7.21 9 5 9c-2.086 0-3.8 1.398-3.984 3.181A1.006 1.006 0 0 1 1 12V4Z"/>
                                    </svg>
                                </div>
                            </a>
                        </div>

                        <div class="col-6">
                            <a href="" class="text-decoration-none text-primary">
                                <div class="shadow border bg-white bg-opacity-95 p-3 rounded hover1">
                                    تغییر اطلاعات
                                    <svg class="mx-1" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-gear" viewBox="0 0 16 16">
                                        <path d="M11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z M8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm.256 7a4.474 4.474 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10c.26 0 .507.009.74.025.226-.341.496-.65.804-.918C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4s1 1 1 1h5.256Zm3.63-4.54c.18-.613 1.048-.613 1.229 0l.043.148a.64.64 0 0 0 .921.382l.136-.074c.561-.306 1.175.308.87.869l-.075.136a.64.64 0 0 0 .382.92l.149.045c.612.18.612 1.048 0 1.229l-.15.043a.64.64 0 0 0-.38.921l.074.136c.305.561-.309 1.175-.87.87l-.136-.075a.64.64 0 0 0-.92.382l-.045.149c-.18.612-1.048.612-1.229 0l-.043-.15a.64.64 0 0 0-.921-.38l-.136.074c-.561.305-1.175-.309-.87-.87l.075-.136a.64.64 0 0 0-.382-.92l-.148-.045c-.613-.18-.613-1.048 0-1.229l.148-.043a.64.64 0 0 0 .382-.921l-.074-.136c-.306-.561.308-1.175.869-.87l.136.075a.64.64 0 0 0 .92-.382l.045-.148ZM14 12.5a1.5 1.5 0 1 0-3 0 1.5 1.5 0 0 0 3 0Z"/>
                                    </svg>
                                </div>
                            </a>
                        </div>

                        <div class="col-6">
                            <a href="" class="text-decoration-none text-primary">
                                <div class="bg-white border bg-white bg-opacity-95 p-3 rounded hover1">
                                    تغییر رمز
                                    <svg class="mx-1" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-pass" viewBox="0 0 16 16">
                                        <path d="M5.5 5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5Zm0 2a.5.5 0 0 0 0 1h3a.5.5 0 0 0 0-1h-3Z"/>
                                        <path d="M8 2a2 2 0 0 0 2-2h2.5A1.5 1.5 0 0 1 14 1.5v13a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 14.5v-13A1.5 1.5 0 0 1 3.5 0H6a2 2 0 0 0 2 2Zm0 1a3.001 3.001 0 0 1-2.83-2H3.5a.5.5 0 0 0-.5.5v13a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5v-13a.5.5 0 0 0-.5-.5h-1.67A3.001 3.001 0 0 1 8 3Z"/>
                                    </svg>
                                </div>
                            </a>
                        </div>

                        <div class="col-6">
                            <a href="" class="text-decoration-none text-primary">
                                <div class="shadow border bg-white bg-opacity-95 p-3 rounded hover1">
                                    درس ها
                                    <svg class="mx-1" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-book-half" viewBox="0 0 16 16">
                                        <path d="M8.5 2.687c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
                                    </svg>
                                </div>
                            </a>
                        </div>

                        <div class="col-6">
                            <a href="" class="text-decoration-none text-primary">
                                <div class="shadow border bg-white bg-opacity-95 p-3 rounded hover1">
                                    تاریخچه خرید
                                    <svg class="mx-1" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-clock-history" viewBox="0 0 16 16">
                                        <path d="M8.515 1.019A7 7 0 0 0 8 1V0a8 8 0 0 1 .589.022l-.074.997zm2.004.45a7.003 7.003 0 0 0-.985-.299l.219-.976c.383.086.76.2 1.126.342l-.36.933zm1.37.71a7.01 7.01 0 0 0-.439-.27l.493-.87a8.025 8.025 0 0 1 .979.654l-.615.789a6.996 6.996 0 0 0-.418-.302zm1.834 1.79a6.99 6.99 0 0 0-.653-.796l.724-.69c.27.285.52.59.747.91l-.818.576zm.744 1.352a7.08 7.08 0 0 0-.214-.468l.893-.45a7.976 7.976 0 0 1 .45 1.088l-.95.313a7.023 7.023 0 0 0-.179-.483zm.53 2.507a6.991 6.991 0 0 0-.1-1.025l.985-.17c.067.386.106.778.116 1.17l-1 .025zm-.131 1.538c.033-.17.06-.339.081-.51l.993.123a7.957 7.957 0 0 1-.23 1.155l-.964-.267c.046-.165.086-.332.12-.501zm-.952 2.379c.184-.29.346-.594.486-.908l.914.405c-.16.36-.345.706-.555 1.038l-.845-.535zm-.964 1.205c.122-.122.239-.248.35-.378l.758.653a8.073 8.073 0 0 1-.401.432l-.707-.707z"/>
                                        <path d="M8 1a7 7 0 1 0 4.95 11.95l.707.707A8.001 8.001 0 1 1 8 0v1z"/>
                                        <path d="M7.5 3a.5.5 0 0 1 .5.5v5.21l3.248 1.856a.5.5 0 0 1-.496.868l-3.5-2A.5.5 0 0 1 7 9V3.5a.5.5 0 0 1 .5-.5z"/>
                                    </svg>
                                </div>
                            </a>
                        </div>

                        <div class="col-6">
                            <a href="" class="text-decoration-none text-primary">
                                <div class="shadow border bg-white bg-opacity-95 p-3 rounded hover1">
                                    پیام ها 
                                    <svg class="mx-1" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-chat-dots" viewBox="0 0 16 16">
                                        <path d="M5 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                                        <path d="m2.165 15.803.02-.004c1.83-.363 2.948-.842 3.468-1.105A9.06 9.06 0 0 0 8 15c4.418 0 8-3.134 8-7s-3.582-7-8-7-8 3.134-8 7c0 1.76.743 3.37 1.97 4.6a10.437 10.437 0 0 1-.524 2.318l-.003.011a10.722 10.722 0 0 1-.244.637c-.079.186.074.394.273.362a21.673 21.673 0 0 0 .693-.125zm.8-3.108a1 1 0 0 0-.287-.801C1.618 10.83 1 9.468 1 8c0-3.192 3.004-6 7-6s7 2.808 7 6c0 3.193-3.004 6-7 6a8.06 8.06 0 0 1-2.088-.272 1 1 0 0 0-.711.074c-.387.196-1.24.57-2.634.893a10.97 10.97 0 0 0 .398-2z"/>
                                    </svg>
                                </div>
                            </a>
                        </div>
                        <div class="col-6">
                            <a href="" class="text-decoration-none text-primary">
                                <div class="shadow border bg-white bg-opacity-95 p-3 rounded hover1">
                                    کلاس انلاین
                                    <svg class="mx-1" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-wifi" viewBox="0 0 16 16">
                                        <path d="M15.384 6.115a.485.485 0 0 0-.047-.736A12.444 12.444 0 0 0 8 3C5.259 3 2.723 3.882.663 5.379a.485.485 0 0 0-.048.736.518.518 0 0 0 .668.05A11.448 11.448 0 0 1 8 4c2.507 0 4.827.802 6.716 2.164.205.148.49.13.668-.049z"/>
                                        <path d="M13.229 8.271a.482.482 0 0 0-.063-.745A9.455 9.455 0 0 0 8 6c-1.905 0-3.68.56-5.166 1.526a.48.48 0 0 0-.063.745.525.525 0 0 0 .652.065A8.46 8.46 0 0 1 8 7a8.46 8.46 0 0 1 4.576 1.336c.206.132.48.108.653-.065zm-2.183 2.183c.226-.226.185-.605-.1-.75A6.473 6.473 0 0 0 8 9c-1.06 0-2.062.254-2.946.704-.285.145-.326.524-.1.75l.015.015c.16.16.407.19.611.09A5.478 5.478 0 0 1 8 10c.868 0 1.69.201 2.42.56.203.1.45.07.61-.091l.016-.015zM9.06 12.44c.196-.196.198-.52-.04-.66A1.99 1.99 0 0 0 8 11.5a1.99 1.99 0 0 0-1.02.28c-.238.14-.236.464-.04.66l.706.706a.5.5 0 0 0 .707 0l.707-.707z"/>
                                    </svg>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-7 shadow shadow border bg-white bg-opacity-95 rounded" style="height: 700px;"></div>
            </div>
        </section>
    </div>
{% endblock body %}

alborz_school_site/templates/account_app/verify_form.html
{% extends 'index.html' %}
{% block title %}تایید ثبت نام {% endblock title %}
{% block body %}
    <div class="py-5 pb-3">
        <section class="container bg-white rounded col-8 col-md-6 col-lg-4 p-4 shadow">
            <h1 class="text-center display-6  mb-3 text-primary">تایید ثبت نام</h1>
            {% comment %} <form action="#" method="post" class="p-3">
                <label for="code_6" class="mt-2">کد شش رقمی</label>
                <input type="text" name="code_6" id="code_6" class="form-control">
                <button type="submit" class="btn btn-block btn-primary form-control my-3">تایید ثبت نام</button>
            </form> {% endcomment %}

            <form action="" method="post">
                {% csrf_token %}
                {{verify_form.as_p}}
                <button type="submit" class="btn btn-primary mb-4">ارسال کد</button>
            </form>
        </section>
    </div>
{% endblock body %}